language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: SnH/Uc9oUqOUkDAAYKUsAlxW+3yY0+Cz+qHQXLKQUUgtsRVU8I4D5kpnxuDXw4Ad2hhD3+Hv/iSeHEAwuHpzJ201tZnP2nXX/LH5D6H5aEzMWSDk78CC0xk7Oe9xTUFBIuJChz0v9QuwnuOFPHRayNJGHkYkBFcKdhH/RzQwGsWKMmWrn9mec3MeR+lDV8uAA7eGqv6pmoNJA5O0lg+vgcLPK23Lg9ucar96xYbZR1rNhN+5+hls8BKr0i03cKup9I6RoHTPYO87vFCbw04LwPWFjBlDIJVK7yEynZHxwbGMW0SwawCRFwrotTMsIIBPZUQESnUkic62W0bqtsgGkyyPGjyvj9qkyQOob4/t/kJt3YBnwPWoCWU0Z0YpjWc5OStmTRrIVMNYzviS6qIahS+2SZd6ETdrZy76g8bvBJhaopA/cVq8E5uUf740/xkZyThnQSKXd3MCtSyZf43ecAcQLlZuECBTG4JY7ZG+ff88VffrclXWrOFdQcNUNHrBfDz2gArgf8PwB0p/8sb28RvHI61gWl7FH1DO3t/GyHAF5RoezjuJaMMMSvm409d8rjJYumEDtyWeLIRIpMEyFW+Goq6U/j4/kW7I3KIplFYtj8sgrK9id2o6khfyusO8oXAf5YTX9V6/Z8vff6v5TbQchyn40hhkgd+LRNnxwwE=
  app: safe-shore-26648
  on:
    repo: rusye/firmy-client
