language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: hPAhcnE7aEmPB1b7OGLvo9XZtvVrt3Ya7fd2Xe+rqE+QJNgTnvGO1usNO8yS6boo2/ECiHJ2vTeF1I/Tg7z7FVQQJU0zd0XrRhAMEWJmH/34Dj6aZb9bHeBsz/VOnye/lx1MCjG6FDuBlUSbkwCnu2BXVRSgPKjvIC5mF2mhkj7ElbzMORlx2b2UtFjqQcVVHVl9AsNoDmKGToO/+eywWLcHPpy2jI1twT3Wa4/q3R5TrYNX7sGvE4GBNKbHfux+a6AU/dHh1+adoXEQAEtkRjYZpkwSAjz4EzwZARPUuV84poOippOAL380ujNtmCUKhA3ROC+FZC6ADzvP+cosKvKXm109i5+KXSu8zN2yMceaS9sdjmszi2plDM5wnBRAUYgVP85kgwUmG/tCy4qLR27Sr02NApPeNpAeZ5RWo2lJtTlDILihG7xzHKCWrDCdCYU3Bj0fefj883Tzz1oQK/RYdGjx4+8xPTtpnTtmc8W+w3Gp2wmn+wVunpu5rL6fSLlGgg7IoaUGa8poW1qnu9j/gEP1a0/GiKyWEm+lJvrc3IckU6S+zRNorjKKJd2bRREjE4cbmc42NPSsqSKESOgISvf3bkxVc1zGuQxVPgpkinX7y8Q03WEg1QbbMrY8349un93d/LL/gxAffqvMBNaT8yvj4iYxGUYpDfNPhj8=
  app: safe-shore-26648
  on:
    repo: rusye/firmy-client
